# Generated by Django 5.0.6 on 2024-07-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employeeeducation_employeeexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company1design',
            new_name='company1desig',
        ),
        migrations.RenameField(
            model_name='employeeexperience',
            old_name='company2design',
            new_name='company2desig',
        ),
    ]
