# Generated by Django 5.0.6 on 2024-07-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_rename_company1design_employeeexperience_company1desig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='company1name',
            new_name='coursepg',
        ),
    ]
